export const en: Record<string, string> = {
  'appTitle': 'WMS System',
  'nav.dashboard': 'Dashboard',
  'nav.cargoItems': 'Cargo',
  'nav.projects': 'Projects',
  'nav.locations': 'Locations',
  'nav.equipment': 'Equipment',
  'nav.movements': 'Movements',
  'nav.sapIntegration': 'SAP Integration',
  'header.dashboard': 'Dashboard',
  'header.cargoManagement': 'Cargo Management',
  'header.projectCargo': 'Project Cargo',
  'header.locations': 'Locations',
  'header.equipmentLifting': 'Equipment & Lifting Gear',
  'header.movementLog': 'Movement Log',
  'header.sapIntegration': 'SAP / ERP Integration',
  'common.add': 'Add', 'common.edit': 'Edit', 'common.delete': 'Delete', 'common.save': 'Save', 'common.cancel': 'Cancel',
  'common.search': 'Search', 'common.filter': 'Filter', 'common.clear': 'Clear', 'common.loading': 'Loading...',
  'common.noDataFound': 'No data found', 'common.systemOnline': 'System Online', 'common.saving': 'Saving...',
  'common.creating': 'Creating...', 'common.recording': 'Recording...', 'common.update': 'Update', 'common.create': 'Create',
  'common.select': 'Select...', 'common.none': 'None', 'common.all': 'All', 'common.allTypes': 'All Types',
  'common.allStatuses': 'All Statuses', 'common.allCategories': 'All Categories', 'common.allCommodities': 'All Commodities',
  'common.confirmDelete': 'Confirm Delete', 'common.actions': 'Actions', 'common.code': 'Code', 'common.name': 'Name',
  'common.type': 'Type', 'common.status': 'Status', 'common.location': 'Location', 'common.previous': 'Previous',
  'common.next': 'Next', 'common.page': 'Page', 'common.of': 'of', 'common.tonnes': 'tonnes', 'common.tons': 'tons',
  'common.items': 'items', 'common.active': 'Active', 'common.inactive': 'Inactive', 'common.collapse': 'Collapse',
  'common.refresh': 'Refresh', 'common.enabled': 'Enabled', 'common.disabled': 'Disabled', 'common.description': 'Description',
  'common.weight': 'Weight', 'common.dimensions': 'Dimensions', 'common.load': 'Load', 'common.progress': 'Progress',
  'common.date': 'Date', 'common.dateSlashTime': 'Date/Time', 'common.remarks': 'Remarks', 'common.operator': 'Operator',
  'common.export': 'Export', 'common.exportCsv': 'Export CSV', 'common.print': 'Print', 'common.bulkActions': 'Bulk Actions',
  'common.selected': 'selected', 'common.changeStatus': 'Change Status', 'common.selectAll': 'Select All',
  'common.close': 'Close', 'common.viewDetails': 'View Details', 'common.total': 'Total',
  'common.language': 'Language', 'common.theme': 'Theme', 'common.dark': 'Dark', 'common.light': 'Light', 'common.system': 'System',
  'footer.left': 'Warehouse Management System v2.0 — Heavy Lift & Project Cargo Operations',
  'footer.right': 'Combi Lift ©',
  'sidebar.footer': 'Heavy Lift Operations - Combi Lift',
  'sidebar.subtitle': 'Warehouse Management',
  'init.wmsSystem': 'Initializing Warehouse Management System...',
  'status.IN_YARD': 'In Yard', 'status.IN_WAREHOUSE': 'In Warehouse', 'status.IN_TRANSIT': 'In Transit',
  'status.RECEIVED': 'Received', 'status.DISPATCHED': 'Dispatched', 'status.DELIVERED': 'Delivered',
  'status.PLANNED': 'Planned', 'status.RECEIVING': 'Receiving', 'status.IN_STORAGE': 'In Storage',
  'status.STAGING': 'Staging', 'status.LOADED': 'Loaded', 'status.SHIPPED': 'Shipped', 'status.COMPLETED': 'Completed',
  'status.AVAILABLE': 'Available', 'status.IN_USE': 'In Use', 'status.MAINTENANCE': 'Maintenance',
  'status.OUT_OF_SERVICE': 'Out of Service',
  'category.HEAVY_LIFT': 'Heavy Lift', 'category.OVERSIZE': 'Oversize', 'category.STANDARD': 'Standard',
  'category.PROJECT_CARGO': 'Project Cargo',
  'commodity.GENERAL': 'General', 'commodity.MACHINERY': 'Machinery', 'commodity.STEEL': 'Steel',
  'commodity.EQUIPMENT': 'Equipment', 'commodity.MODULE': 'Module',
  'equipmentType.CRANE': 'Crane', 'equipmentType.FORKLIFT': 'Forklift', 'equipmentType.SPREADER_BAR': 'Spreader Bar',
  'equipmentType.SLING': 'Sling', 'equipmentType.SHACKLE': 'Shackle', 'equipmentType.BEAM': 'Lifting Beam',
  'equipmentType.JACK': 'Hydraulic Jack', 'equipmentType.ROLLER': 'Rollers',
  'movementType.RECEIVE': 'Receive', 'movementType.MOVE': 'Move', 'movementType.DISPATCH': 'Dispatch',
  'movementType.INSPECT': 'Inspect',
  'locationType.YARD': 'Yard', 'locationType.WAREHOUSE': 'Warehouse', 'locationType.OPEN_AREA': 'Open Area',
  'locationType.STAGING': 'Staging Area', 'locationType.BERTH': 'Berth',
  'syncStatus.PENDING': 'Pending', 'syncStatus.SENT': 'Sent', 'syncStatus.SUCCESS': 'Success',
  'syncStatus.FAILED': 'Failed', 'syncStatus.RETRYING': 'Retrying',
  'syncDirection.OUTBOUND': 'Outbound', 'syncDirection.INBOUND': 'Inbound',
  'dashboard.title': 'Dashboard', 'dashboard.subtitle': 'Heavy Lift Operations Overview',
  'dashboard.totalCargo': 'Total Cargo', 'dashboard.inYardStorage': 'Yard/Storage', 'dashboard.activeProjects': 'Active Projects',
  'dashboard.equipmentAvail': 'Equip. Available', 'dashboard.totalWeight': 'Total Weight', 'dashboard.pendingDispatch': 'Pending Dispatch',
  'dashboard.cargoStatusBreakdown': 'Cargo Status Distribution', 'dashboard.liftCategoryDistribution': 'Lift Category Distribution',
  'dashboard.recentMovements': 'Recent Movements', 'dashboard.projectProgress': 'Project Progress',
  'dashboard.ref': 'Ref', 'dashboard.cargo': 'Cargo', 'dashboard.type': 'Type',
  'dashboard.from': 'From', 'dashboard.to': 'To', 'dashboard.movementsTrend': 'Movements Trend (Last 7 Days)',
  'dashboard.weightByCategory': 'Weight by Category (tonnes)', 'dashboard.locationUtilization': 'Location Utilization',
  'dashboard.movements': 'Movements', 'dashboard.receive': 'Receive', 'dashboard.move': 'Move',
  'dashboard.dispatch': 'Dispatch', 'dashboard.day': 'Day', 'dashboard.count': 'Count',
  'welcome.title': 'Welcome to WMS', 'welcome.subtitle': 'Comprehensive Heavy Lift & Project Cargo Management',
  'welcome.guideStep1.title': 'Cargo', 'welcome.guideStep1.description': 'Manage and track all warehouse cargo items',
  'welcome.guideStep2.title': 'Projects', 'welcome.guideStep2.description': 'Track shipping projects and their progress',
  'welcome.guideStep3.title': 'Locations', 'welcome.guideStep3.description': 'Manage storage locations (yards, warehouses, berths)',
  'welcome.guideStep4.title': 'Equipment', 'welcome.guideStep4.description': 'Track cranes, lifting gear, and certifications',
  'welcome.guideStep5.title': 'Movements', 'welcome.guideStep5.description': 'Complete movement log for all cargo operations',
  'cargo.title': 'Cargo', 'cargo.subtitle': 'Manage all cargo items in the warehouse', 'cargo.addCargo': 'Add Cargo',
  'cargo.searchPlaceholder': 'Search by code, description...', 'cargo.table.code': 'Code', 'cargo.table.description': 'Description',
  'cargo.table.weight': 'Weight (kg)', 'cargo.table.dimensions': 'Dimensions (L×W×H)', 'cargo.table.category': 'Category',
  'cargo.table.status': 'Status', 'cargo.table.location': 'Location', 'cargo.table.project': 'Project',
  'cargo.table.actions': 'Actions', 'cargo.noCargoFound': 'No cargo found', 'cargo.editCargo': 'Edit Cargo',
  'cargo.addNewCargo': 'Add New Cargo', 'cargo.form.description': 'Description *', 'cargo.form.weight': 'Weight (kg) *',
  'cargo.form.dimensions': 'Dimensions (m)', 'cargo.form.liftCategory': 'Lift Category *', 'cargo.form.commodityType': 'Commodity Type *',
  'cargo.form.project': 'Project', 'cargo.form.clientName': 'Client Name', 'cargo.form.poReference': 'PO Reference',
  'cargo.form.blReference': 'BL Reference', 'cargo.form.centerOfGravity': 'Center of Gravity',
  'cargo.form.cogPlaceholder': 'e.g., 5.2m from base', 'cargo.form.liftingPoints': 'Lifting Points',
  'cargo.form.liftingPointsPlaceholder': 'Number of points', 'cargo.form.specialHandling': 'Special Handling',
  'cargo.form.specialHandlingPlaceholder': 'Any special handling requirements...', 'cargo.details.title': 'Cargo Details —',
  'cargo.details.description': 'Description:', 'cargo.details.weight': 'Weight:', 'cargo.details.dimensions': 'Dimensions:',
  'cargo.details.category': 'Category:', 'cargo.details.status': 'Status:', 'cargo.details.location': 'Location:',
  'cargo.details.project': 'Project:', 'cargo.details.commodity': 'Commodity:', 'cargo.details.client': 'Client:',
  'cargo.details.poRef': 'PO Ref:', 'cargo.details.blRef': 'BL Ref:', 'cargo.details.cog': 'COG:',
  'cargo.details.liftingPoints': 'Lifting Points:', 'cargo.details.specialHandling': 'Special Handling:',
  'cargo.details.unassigned': 'Unassigned', 'cargo.delete.message': 'Are you sure you want to delete',
  'cargo.delete.cannotUndo': '? This action cannot be undone.', 'cargo.toast.fetchFailed': 'Failed to fetch cargo items',
  'cargo.toast.created': 'Cargo item created', 'cargo.toast.updated': 'Cargo item updated', 'cargo.toast.deleted': 'Cargo item deleted',
  'cargo.toast.deleteFailed': 'Failed to delete cargo item', 'cargo.toast.saveFailed': 'Failed to save',
  'cargo.toast.exported': 'Cargo exported successfully',
  'projects.title': 'Projects', 'projects.subtitle': 'Track project cargo and shipments', 'projects.addProject': 'Add Project',
  'projects.backToProjects': 'Back to Projects', 'projects.cargoItems': 'Project Cargo', 'projects.noCargoItems': 'No cargo items',
  'projects.noProjectsFound': 'No projects found', 'projects.table.code': 'Code', 'projects.table.description': 'Description',
  'projects.table.weight': 'Weight (kg)', 'projects.table.category': 'Category', 'projects.table.status': 'Status',
  'projects.table.location': 'Location', 'projects.card.items': 'items', 'projects.card.weight': 'tonnes', 'projects.card.vol': 'vol',
  'projects.card.itemsLabel': 'Items:', 'projects.card.weightLabel': 'Weight:', 'projects.card.volLabel': 'Volume:',
  'projects.tbd': 'TBD', 'projects.addNewProject': 'Add New Project', 'projects.form.projectName': 'Project Name *',
  'projects.form.description': 'Description', 'projects.form.clientName': 'Client Name *', 'projects.form.clientContact': 'Client Contact',
  'projects.form.destination': 'Destination', 'projects.form.shippingLine': 'Shipping Line', 'projects.form.vesselName': 'Vessel Name',
  'projects.form.etd': 'ETD', 'projects.form.eta': 'ETA', 'projects.toast.fetchFailed': 'Failed to fetch projects',
  'projects.toast.created': 'Project created', 'projects.toast.createFailed': 'Failed to create project',
  'projects.toast.cargoFetchFailed': 'Failed to fetch project cargo', 'projects.toast.exported': 'Projects exported successfully',
  'detail.overview': 'Overview',
  'detail.cargo': 'Cargo',
  'detail.movements': 'Movements',
  'detail.timeline': 'Timeline',
  'detail.quickActions': 'Quick Actions',
  'detail.changeStatus': 'Change Status',
  'detail.assignLocation': 'Assign Location',
  'detail.recordMovement': 'Record Movement',
  'detail.movementHistory': 'Movement History',
  'detail.noMovements': 'No movements recorded',
  'detail.statusChanged': 'Status changed successfully',
  'detail.locationAssigned': 'Location assigned',
  'detail.statusChangeFailed': 'Failed to change status',
  'detail.workflow.title': 'Status Workflow',
  'detail.workflow.current': 'Current Status',
  'detail.workflow.next': 'Next Step',
  'detail.info.specifications': 'Specifications',
  'detail.info.references': 'References',
  'detail.info.shipping': 'Shipping',
  'detail.info.volume': 'Volume',
  'detail.info.createdAt': 'Created At',
  'detail.info.receivedAt': 'Received At',
  'detail.info.dispatchedAt': 'Dispatched At',
  'detail.cargo.clickToView': 'Click to view details',
  'detail.cargo.weightUnit': 'kg',
  'detail.cargo.viewDetail': 'View Details',
  'detail.cargo.changeCargoStatus': 'Change Cargo Status',
  'detail.cargo.moveCargo': 'Move Cargo',
  'detail.cargo.removeFromProject': 'Remove from Project',
  'detail.project.statusManagement': 'Project Status Management',
  'detail.project.changeStatus': 'Change Project Status',
  'detail.project.statusChanged': 'Project status changed',
  'detail.project.overview.title': 'Project Summary',
  'detail.project.overview.description': 'Description',
  'detail.project.overview.client': 'Client',
  'detail.project.overview.contact': 'Client Contact',
  'detail.project.overview.destination': 'Destination',
  'detail.project.overview.shippingLine': 'Shipping Line',
  'detail.project.overview.vessel': 'Vessel',
  'detail.project.stats.totalItems': 'Total Items',
  'detail.project.stats.totalWeight': 'Total Weight',
  'detail.project.stats.totalVolume': 'Total Volume',
  'detail.project.stats.byStatus': 'By Status',
  'detail.project.stats.completion': 'Completion',
  'detail.project.editProject': 'Edit Project',
  'detail.project.exportReport': 'Export Report',
  'detail.project.timeline': 'Activity Timeline',
  'detail.project.daysElapsed': 'days elapsed',
  'detail.project.daysRemaining': 'days remaining',
  'detail.project.cargoStatusBreakdown': 'Cargo Status Distribution',
  'detail.project.noActivity': 'No activity recorded yet',
  'detail.project.shippingTimeline': 'Shipping Timeline',
  'detail.location.itemsStored': 'Stored Items',
  'detail.location.noItems': 'No items at this location',
  'detail.location.capacity': 'Used Capacity',
  'detail.location.free': 'Free',
  'detail.photos.title': 'Photos & Attachments',
  'detail.photos.upload': 'Upload',
  'detail.documents.title': 'Documents',
  'detail.documents.bl': 'Bill of Lading',
  'detail.documents.po': 'Purchase Order',
  'detail.documents.inspection': 'Inspection Report',
  'detail.documents.certificate': 'Certificate',
  'detail.quickActions.recordMovement': 'Record Movement',
  'detail.quickActions.printLabel': 'Print Label',
  'detail.quickActions.generateQR': 'Generate QR',
  'locations.title': 'Locations', 'locations.subtitle': 'Manage warehouse yards and storage locations',
  'locations.addLocation': 'Add Location', 'locations.allTypes': 'All Types', 'locations.noLocationsFound': 'No locations found',
  'locations.card.zone': 'Zone', 'locations.card.capacity': 'Capacity', 'locations.card.dimensions': 'Dimensions',
  'locations.card.area': 'Area', 'locations.card.items': 'items', 'locations.card.load': 'Load',
  'locations.editLocation': 'Edit Location', 'locations.addNewLocation': 'Add New Location', 'locations.form.code': 'Code *',
  'locations.form.name': 'Name *', 'locations.form.type': 'Type *', 'locations.form.zone': 'Zone',
  'locations.form.maxWeight': 'Max Weight (tonnes)', 'locations.form.maxDimension': 'Max Dimension',
  'locations.form.maxDimensionPlaceholder': 'e.g., 50×30×25', 'locations.form.area': 'Area (m²)', 'locations.form.active': 'Active',
  'locations.delete.message': 'Delete Location', 'locations.delete.warning': '? Cannot delete locations with cargo.',
  'locations.toast.fetchFailed': 'Failed to fetch locations', 'locations.toast.created': 'Location created',
  'locations.toast.updated': 'Location updated', 'locations.toast.deleted': 'Location deleted',
  'locations.toast.deleteFailed': 'Failed to delete location', 'locations.toast.exported': 'Locations exported successfully',
  'equipment.title': 'Equipment', 'equipment.subtitle': 'Manage cranes, forklifts, and lifting gear',
  'equipment.addEquipment': 'Add Equipment', 'equipment.noEquipmentFound': 'No equipment found',
  'equipment.table.code': 'Code', 'equipment.table.name': 'Name', 'equipment.table.type': 'Type', 'equipment.table.capacity': 'Capacity',
  'equipment.table.manufacturer': 'Manufacturer', 'equipment.table.status': 'Status', 'equipment.table.location': 'Location',
  'equipment.table.certExpiry': 'Cert. Expiry', 'equipment.table.actions': 'Actions',
  'equipment.certExpired': 'Certificate Expired', 'equipment.certExpiringSoon': 'Expires within 30 days',
  'equipment.editEquipment': 'Edit Equipment', 'equipment.addNewEquipment': 'Add New Equipment', 'equipment.form.name': 'Name *',
  'equipment.form.type': 'Type *', 'equipment.form.capacity': 'Capacity (tonnes)', 'equipment.form.status': 'Status *',
  'equipment.form.manufacturer': 'Manufacturer', 'equipment.form.model': 'Model', 'equipment.form.serialNumber': 'Serial Number',
  'equipment.form.currentLocation': 'Current Location', 'equipment.form.lastInspection': 'Last Inspection',
  'equipment.form.nextInspection': 'Next Inspection', 'equipment.form.certificationId': 'Certification ID',
  'equipment.form.certExpiry': 'Cert. Expiry', 'equipment.delete.message': 'Delete Equipment',
  'equipment.delete.cannotUndo': '? This action cannot be undone.', 'equipment.toast.fetchFailed': 'Failed to fetch equipment',
  'equipment.toast.created': 'Equipment created', 'equipment.toast.updated': 'Equipment updated',
  'equipment.toast.deleted': 'Equipment deleted', 'equipment.toast.deleteFailed': 'Failed to delete equipment',
  'equipment.toast.exported': 'Equipment exported successfully',
  'movements.title': 'Movements', 'movements.subtitle': 'Movement log and audit trail', 'movements.recordMovement': 'Record Movement',
  'movements.searchPlaceholder': 'Cargo code...', 'movements.table.ref': 'Ref', 'movements.table.dateTime': 'Date/Time',
  'movements.table.cargo': 'Cargo', 'movements.table.type': 'Type', 'movements.table.from': 'From', 'movements.table.to': 'To',
  'movements.table.equipment': 'Equipment', 'movements.table.operator': 'Operator', 'movements.table.weight': 'Weight',
  'movements.table.remarks': 'Remarks', 'movements.noMovementsFound': 'No movements found',
  'movements.recordNewMovement': 'Record New Movement', 'movements.form.cargoItem': 'Cargo Item *',
  'movements.form.cargoPlaceholder': 'Search and select cargo...', 'movements.form.movementType': 'Movement Type *',
  'movements.form.liftMethod': 'Lift Method', 'movements.form.liftMethodPlaceholder': 'e.g., Crane, Forklift',
  'movements.form.fromLocation': 'From Location', 'movements.form.toLocation': 'To Location',
  'movements.form.equipmentUsed': 'Equipment Used', 'movements.form.operatorName': 'Operator',
  'movements.form.actualWeight': 'Actual Weight (kg)', 'movements.form.remarks': 'Remarks',
  'movements.form.remarksPlaceholder': 'Optional remarks...', 'movements.toast.fetchFailed': 'Failed to fetch movements',
  'movements.toast.recorded': 'Movement recorded', 'movements.toast.recordFailed': 'Failed to record movement',
  'movements.toast.exported': 'Movements exported successfully',
  'integration.title': 'SAP Integration', 'integration.subtitle': 'Event-driven SAP integration configuration',
  'integration.saveConfiguration': 'Save Configuration', 'integration.eventDrivenTitle': 'Event-Driven Architecture',
  'integration.eventDrivenDesc': 'The WMS uses an event-driven pattern to sync with SAP.',
  'integration.syncHealth': 'Sync Health', 'integration.successful': 'Successful', 'integration.failed': 'Failed',
  'integration.connectionConfig': 'SAP Connection Config', 'integration.connectionConfigDesc': 'Configure connection to SAP ERP',
  'integration.form.endpoint': 'SAP Endpoint', 'integration.form.authMethod': 'Auth Method', 'integration.form.apiKey': 'API Key',
  'integration.form.protocol': 'Protocol', 'integration.form.sapSystemId': 'SAP System ID', 'integration.form.client': 'Client',
  'integration.form.enableSync': 'Enable SAP Sync', 'integration.eventMapping': 'Event Mapping',
  'integration.eventMappingDesc': 'Map system events to SAP endpoints', 'integration.table.eventType': 'Event Type',
  'integration.table.sapEndpoint': 'SAP Endpoint', 'integration.table.method': 'Method', 'integration.table.enabled': 'Enabled',
  'integration.syncLog': 'Sync Log', 'integration.syncLogDesc': 'Recent sync activity', 'integration.table.event': 'Event',
  'integration.table.direction': 'Direction', 'integration.table.timestamp': 'Timestamp', 'integration.table.retries': 'Retries',
  'integration.toast.configSaved': 'SAP config saved (demo)', 'integration.toast.mappingToggled': 'Event mapping updated',
  'integration.toast.logRefreshed': 'Sync log refreshed (demo)', 'integration.direction.outbound': 'WMS → SAP',
  'integration.direction.inbound': 'SAP → WMS',
  // ===== Equipment Detail =====
  'detail.equipment.profile': 'Equipment Profile',
  'detail.equipment.certification': 'Certification Status',
  'detail.equipment.maintenance': 'Maintenance Schedule',
  'detail.equipment.capacity': 'Capacity Utilization',
  'detail.equipment.recordInspection': 'Record Inspection',
  'detail.equipment.scheduleMaintenance': 'Schedule Maintenance',
  'detail.equipment.printCertificate': 'Print Certificate',
  'detail.equipment.specifications': 'Specifications',
  'detail.equipment.capacityTons': 'Capacity',
  'detail.equipment.manufacturer': 'Manufacturer',
  'detail.equipment.model': 'Model',
  'detail.equipment.serialNumber': 'Serial Number',
  'detail.equipment.currentLocation': 'Current Location',
  'detail.equipment.certId': 'Certification ID',
  'detail.equipment.certExpiryDate': 'Cert. Expiry Date',
  'detail.equipment.certValid': 'Valid',
  'detail.equipment.certExpiring': 'Expiring Soon',
  'detail.equipment.certExpired': 'Expired',
  'detail.equipment.certNone': 'No Certification',
  'detail.equipment.daysRemaining': 'days remaining',
  'detail.equipment.daysOverdue': 'days overdue',
  'detail.equipment.lastInspection': 'Last Inspection',
  'detail.equipment.nextInspection': 'Next Inspection',
  'detail.equipment.inspectionProgress': 'Inspection Progress',
  'detail.equipment.currentLoad': 'Current Load',
  'detail.equipment.maxCapacity': 'Max Capacity',
  'detail.equipment.utilization': 'Utilization',
  'detail.equipment.noCapacity': 'No capacity data',
  'detail.equipment.statusManagement': 'Status Management',
  'detail.equipment.changeStatus': 'Change Status',
  'detail.equipment.statusChanged': 'Equipment status changed',
  'detail.equipment.statusChangeFailed': 'Failed to change status',
  'detail.equipment.noNextInspection': 'No next inspection scheduled',
  'detail.equipment.editEquipment': 'Edit Equipment',
  'detail.equipment.noLocation': 'Not assigned',
  'detail.equipment.emptyState': 'No equipment found. Add your first equipment item.',
  'detail.location.occupancy': 'Occupancy',
  'detail.location.cargoInventory': 'Cargo Inventory',
  'detail.location.mapView': 'Map View',
  'detail.location.mapViewComingSoon': 'Map View Coming Soon',
  'detail.location.assignCargo': 'Assign Cargo',
  'detail.location.transferAll': 'Transfer All',
  'detail.location.printLabel': 'Print Location Label',
  'detail.location.maxWeight': 'Max Weight',
  'detail.location.area': 'Area',
  'detail.location.zone': 'Zone',
  'detail.location.usedOf': 'of',
  'detail.location.currentLoad': 'Current Load',
  'detail.location.emptyState': 'No locations found. Add your first storage location.',
  'detail.location.quickActions': 'Quick Actions',
  'detail.location.editLocation': 'Edit Location',
  'detail.location.deleteLocation': 'Delete Location',
  'detail.location.cargoCount': 'Cargo',
  'detail.location.occupancyRate': 'Occupancy Rate',
  'detail.location.noCargo': 'No cargo at this location',
  'locations.gridView': 'Grid',
  'locations.tableView': 'Table',
  'locations.table.code': 'Code',
  'locations.table.name': 'Name',
  'locations.table.type': 'Type',
  'locations.table.zone': 'Zone',
  'locations.table.capacity': 'Capacity',
  'locations.table.area': 'Area',
  'locations.table.cargoCount': 'Cargo',
  'locations.table.status': 'Status',
  'locations.table.actions': 'Actions',
  'locations.searchPlaceholder': 'Search locations...',
  'equipment.form.specifications': 'Specifications',
  'equipment.form.inspectionCertification': 'Inspection & Certification',
  'equipment.form.capacitySlider': 'Capacity',
  // ===== Movement Detail =====
  'detail.movement.path': 'Movement Path',
  'detail.movement.cargoInfo': 'Cargo Information',
  'detail.movement.operator': 'Operator',
  'detail.movement.equipment': 'Equipment Used',
  'detail.movement.fullTimeline': 'Full Movement Timeline',
  'detail.movement.fromLocation': 'From Location',
  'detail.movement.toLocation': 'To Location',
  'detail.movement.noLocation': 'No location assigned',
  'detail.movement.remarks': 'Remarks',
  'detail.movement.liftMethod': 'Lift Method',
  'detail.movement.actualWeight': 'Actual Weight',
  'detail.movement.performedBy': 'Performed By',
  'detail.movement.cargoCode': 'Cargo Code',
  'detail.movement.cargoDescription': 'Description',
  'detail.movement.cargoWeight': 'Weight',
  'detail.movement.cargoCategory': 'Category',
  'detail.movement.cargoStatus': 'Status',
  'detail.movement.noTimeline': 'No movement history for this cargo',
  'detail.movement.movementDetails': 'Movement Details',
  'movements.stats.today': 'Today',
  'movements.stats.thisWeek': 'This Week',
  'movements.stats.received': 'Received',
  'movements.stats.dispatched': 'Dispatched',
  'movements.stats.movements': 'Movements',
  'movements.live': 'Live',
  'movements.autoRefresh': 'Auto Refresh',
  'movements.dateFrom': 'From Date',
  'movements.dateTo': 'To Date',
};
